cl /EHsc get_GBP.cpp magsv.lib
cl /EHsc get_amp_gain_bandwidth.cpp magsv.lib
cl /EHsc get_amp_gain_sign.cpp magsv.lib
cl /EHsc get_amp_or_fll.cpp magsv.lib
cl /EHsc get_channel_info.cpp magsv.lib
cl /EHsc get_dummy.cpp magsv.lib
cl /EHsc get_feedback_resistor.cpp magsv.lib
cl /EHsc get_generator_onoff.cpp magsv.lib
cl /EHsc get_generator_params.cpp magsv.lib
cl /EHsc get_output_coupling.cpp magsv.lib
cl /EHsc get_squid_bias.cpp magsv.lib
cl /EHsc get_tes_current_bias.cpp magsv.lib
cl /EHsc set_GBP.cpp magsv.lib
cl /EHsc set_amp_gain_bandwidth.cpp magsv.lib
cl /EHsc set_amp_gain_sign.cpp magsv.lib
cl /EHsc set_amp_or_fll.cpp magsv.lib
cl /EHsc set_dummy.cpp magsv.lib
cl /EHsc set_feedback_resistor.cpp magsv.lib
cl /EHsc set_generator_onoff.cpp magsv.lib
cl /EHsc set_generator_params.cpp magsv.lib
cl /EHsc set_output_coupling.cpp magsv.lib
cl /EHsc set_squid_bias.cpp magsv.lib
cl /EHsc set_tes_current_bias.cpp magsv.lib
